version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pry
    versions:
    - 0.13.1
    - 0.14.0
  - dependency-name: unicorn
    versions:
    - 5.8.0
  - dependency-name: fabrication
    versions:
    - 2.21.1
